declare module 'vue-template-compiler/build'
declare module 'strip-ansi'
// declare module 'fs-extra'
declare module 'log-horizon'
declare module 'prismjs'
declare module 'prismjs/components'
declare module 'carlo'
declare module 'chokidar'
declare module 'sao'
declare module 'get-port'
